import 'package:flutter_test/flutter_test.dart';
import 'package:reportdeepen/l10n/app_strings.dart';
import 'package:reportdeepen/services/auth_error_message.dart';

void main() {
  group('authErrorMessage', () {
    test('translates invalid login credentials to Russian', () {
      expect(
        authErrorMessage(_strings('ru'), 'Invalid login credentials'),
        'Неверный логин или пароль',
      );
    });

    test('translates invalid login credentials to Kazakh', () {
      expect(
        authErrorMessage(_strings('kk'), 'Invalid login credentials'),
        'Логин немесе құпиясөз дұрыс емес',
      );
    });

    test('translates duplicate login to Russian', () {
      expect(
        authErrorMessage(_strings('ru'), 'User already registered'),
        'Такой логин уже занят',
      );
    });

    test('translates duplicate login to Kazakh', () {
      expect(
        authErrorMessage(_strings('kk'), 'User already registered'),
        'Бұл логин бос емес',
      );
    });

    test('keeps unknown messages unchanged', () {
      expect(authErrorMessage(_strings('ru'), 'Something else'), 'Something else');
    });
  });
}

AppStrings _strings(String languageCode) {
  return AppStrings(
    languageCode: languageCode,
    appTitle: '',
    back: '',
    cancel: '',
    yes: '',
    no: '',
    save: '',
    add: '',
    delete: '',
    remove: '',
    error: '',
    loading: '',
    close: '',
    codeCopied: '',
    retry: '',
    appSubtitle: '',
    signInGoogle: '',
    signingIn: '',
    noPassword: '',
    notRegistered: '',
    appLocked: '',
    unlock: '',
    switchAccount: '',
    accessDenied: '',
    notAllowedDesc: '',
    profileNotLoaded: '',
    googleAccountRequiredTitle: '',
    googleAccountRequiredMessage: '',
    openSettings: '',
    selectGroup: '',
    groupSubtitle: '',
    availableGroups: '',
    noGroupsHint: '',
    currentLabel: '',
    createNewGroup: '',
    groupNameHint: '',
    create: '',
    creating: '',
    tabList: '',
    tabReport: '',
    tabAdmin: '',
    tabCodes: '',
    tabProfile: '',
    tabPayments: '',
    allGroups: '',
    noGroupSelected: '',
    selectGroupBtn: '',
    logout: '',
    groupLabel: '',
    language: '',
    colorTheme: '',
    kazakh: '',
    russian: '',
    adminTitle: '',
    superAdminLabel: '',
    groupAdminLabel: '',
    memberCount: '',
    noMembers: '',
    codeLabel: '',
    deleteGroup: '',
    deleteGroupConfirm: '',
    removeAdmin: '',
    makeAdmin: '',
    removeFinancier: '',
    makeFinancier: '',
    financierRemoved: '',
    financierAssigned: '',
    changeGroup: '',
    removeMember: '',
    removeMemberConfirm: '',
    noOtherGroups: '',
    selectNewGroup: '',
    addUser: '',
    groupNameLabel: '',
    startDateOptional: '',
    selectStartDate: '',
    groupCreated: '',
    userAdded: '',
    userAutoJoin: '',
    userAlreadyInGroup: '',
    userInOtherGroup: '',
    removedFromGroup: '',
    adminRemoved: '',
    adminAssigned: '',
    updateFailed: '',
    addFailed: '',
    myAdminsTitle: '',
    noAdmins: '',
    ungroupedUsers: '',
    ungroupedUsersDesc: '',
    maxValuesTitle: '',
    maxValuesHint: '',
    periodHasReports: '',
    periods: '',
    noPeriods: '',
    createPeriod: '',
    myPeriodTitle: '',
    periodStart: '',
    periodEnd: '',
    periodCreated: '',
    selectDate: '',
    allowlist: '',
    allowedEmails: '',
    noAllowedEmails: '',
    addEmail: '',
    removeFromList: '',
    financierLabel: '',
    paymentsTitle: '',
    allMembers: '',
    thisMonth: '',
    total: '',
    paidLabel: '',
    unpaidLabel: '',
    noPayments: '',
    addPayment: '',
    editPayment: '',
    amountLabel: '',
    paymentDate: '',
    selectPaymentDate: '',
    monthlyPayment: '',
    extraPayment: '',
    paidStatus: '',
    unpaidStatus: '',
    extraLabel: '',
    monthlyLabel: '',
    allPaymentsLabel: '',
    timesUnit: '',
    deletePaymentConfirm: '',
    switchGroupTitle: '',
    fixedMonthlyAmount: '',
    fixedAmountHint: '',
    fixedAmountLabel: '',
    partiallyPaidLabel: '',
    partiallyPaidStatus: '',
    remainingDebtLabel: '',
    editFixedAmount: '',
    weekLabel: '',
    monthLabel: '',
    noReport: '',
    myReport: '',
    allReports: '',
    viewDetail: '',
    reportSaved: '',
    reportSaving: '',
    manualValueTitle: '',
    waitingForGroup: '',
    waitingDesc: '',
    inviteCodeTitle: '',
    inviteCodeSubtitle: '',
    inviteCodeCheck: '',
    inviteCodeNotFound: '',
    inviteCodeExpired: '',
    inviteCodeUsed: '',
    generateAdminCode: '',
    generateUserCode: '',
    activeCode: '',
    noActiveCode: '',
    codeExpiresIn: '',
    greeting: '',
    switchGroupShort: '',
    noPeriodSelected: '',
    autoCalculated: '',
    milestoneStart: '',
    milestoneKeepGoing: '',
    milestoneHalfWay: '',
    milestoneGoodProgress: '',
    milestoneExcellent: '',
    groupProgress: '',
    perWeek: '',
    paymentUnit: '',
    youLabel: '',
    membersTitle: '',
    memberRoleLabel: '',
    currentWeekLabel: '',
    weeksAgoSuffix: '',
    customCatsTitle: '',
    customCatsHint: '',
    customCatAdd: '',
    customCatNewTitle: '',
    customCatIconLabel: '',
    customCatNameLabel: '',
    customCatNameHint: '',
    customCatUnitLabel: '',
    customCatMaxLabel: '',
    customCatScoringAmountLabel: '',
    customCatScoringAmountOptionalLabel: '',
    customCatPointsValueLabel: '',
    customCatEmptyTitle: '',
    customCatEmptyHint: '',
    metricCannotDeleteTitle: '',
    metricCannotDeleteMsg: '',
    metricDeleteTitle: '',
    adminPersonalMetricsHint: '',
    pinCode: '',
    pinEnabled: '',
    pinDisabled: '',
    pinSetup: '',
    pinChange: '',
    pinDisable: '',
    pinEnter: '',
    pinNewCode: '',
    pinConfirm: '',
    pinWrong: '',
    pinMismatch: '',
    registrationTitle: '',
    nicknameLabel: '',
    nicknameHint: '',
    inviteCodeLabel: '',
    inviteCodeShortHint: '',
    submitRegistration: '',
    errorNicknameTaken: '',
    errorNicknameInvalid: '',
    errorInviteInvalid: '',
    errorInviteExpired: '',
  );
}
